language: go

# The feature/go15 branch uses new features in go15. Only testing this branch
# against tip which has the features.
go:
  - 1.5

# Setting sudo access to false will let Travis CI use containers rather than
# VMs to run the tests. For more details see:
# - http://docs.travis-ci.com/user/workers/container-based-infrastructure/
# - http://docs.travis-ci.com/user/workers/standard-infrastructure/
sudo: false

install: make bootstrap

# The default script is go test -v ./... which will test everything
# in the vendor directory. We don't need to test all dependent packages.
# Only testing this project.
script:
  - GO15VENDOREXPERIMENT=1 go test -v . ./cmd ./gb ./util ./cfg

notifications:
  irc: "irc.freenode.net#masterminds"
